//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using UnityEngine;
using game.manager.asset;
using game.view.gameplay.component.action;
using game.view.gameplay.component.collider;

namespace game.view.gameplay.component.bullet
{
	public class BulletSystem : MonoBehaviour
	{

		private ArrayList _bullets = new ArrayList();

		public GameObject createBullet(Vector3 position)
		{
			GameObject bulletPrefab = (GameObject)AssetManager.getInstance().getAsset(AssetConstant.GAME, "Assets/Resources/game/weapon/bulletPrefab");
			GameObject bullet = GameObject.Instantiate (bulletPrefab);
			bullet.name = "Bullet";
			bullet.AddComponent<MoveComponent> ();
			bullet.AddComponent<ColliderSystem> ();
			
			bullet.transform.SetParent (GameView.getMap().transform.FindChild("ObjectContainer"));
			bullet.transform.localPosition = position;

			addBullet (bullet);

			return bullet;
		}
		public void destroyBullet(GameObject bullet)
		{
			_bullets.Remove (bullet);
			GameObject.Destroy (bullet);
		}
		public void addBullet(GameObject bullet)
		{
			_bullets.Add (bullet);
		}
		public void removeBullet(GameObject bullet)
		{
			_bullets.Remove (bullet);
		}


	}
}

